print("What is your name?")
name = str(input())
print ("How old are you?")
age = int(input())
print ("Where are you from?")
place = str(input())
print ("This is ",name)
print ("(S)he is" ,age,"years old")
print ("(S)he live in",place)

